language: java
jdk:
  - openjdk8

before_install:
 - chmod +x gradlew

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

notifications:
  email: false
  irc:
    channels:
      - "irc.esper.net#ruby"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{commit_message} by %{author}): %{message}  Details: %{build_url}  Changes: %{compare_url}"
    use_notice: true
    # nick: travis-ci

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/